trigger:
  - master
variables:
  - group: uipath-cicd
  - name: agent.preferPowerShellOnContainers
    value: "True"

stages:
  - stage: Build
    displayName: Create build artifact
    jobs:
      - job: BuildArtifact
        pool:
          vmImage: "windows-latest"
        container:
          image: uipathjenkinsdemo.azurecr.io/uipathrepository:latest
          endpoint: uipathjenkinsdemo

        steps:
          - script: C:\UiPath\UiRobot.exe pack $(Build.SourcesDirectory)\project.json -o $(Build.ArtifactStagingDirectory)\ -v 1.0.$(Build.BuildNumber)
            displayName: "Build the artifact"
          - publish: $(Build.ArtifactStagingDirectory)
            artifact: drop
            
  - stage: DeployUat
    displayName: Deploy build artifact to UAT
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: deployUat
        displayName: Deploy package to UAT Orchestrator
        pool:
          vmImage: "windows-latest"
        container:
          image: uipathjenkinsdemo.azurecr.io/uipathrepository:latest
          endpoint: uipathjenkinsdemo
        environment: uat
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  displayName: 'Download Pipeline Artifact'
                  inputs:
                    path: $(Build.SourcesDirectory)
                - powershell: |
                    Import-Module UiPath.Powershell
                    $token = Get-UiPathAuthToken -Verbose Get-UiPathAuthToken -ClientId '8DEv1AMNXczW3y4U15LL3jYf62jK93n5' -UserKey 'SMQuXkSoYQ5BYj_qS1orVzuxfAPAFaizS1ru_eI8HIQ9K' -AccountName 'darkelfaxe' -CloudDeployment 'Production' -TenantName 'darkelfaxe'
                    Add-UiPathPackage -PackageFile $(Build.SourcesDirectory)\drop\CI-CD-Robot.1.0.$(Build.BuildNumber).nupkg -AuthToken $token