trigger:
  - master
variables:
  - group: uipath-cicd
  - name: agent.preferPowerShellOnContainers
    value: "True"

stages:
  - stage: Build
    displayName: Create build artifact
    jobs:
      - job: BuildArtifact
        pool:
          vmImage: "windows-latest"
        container:
          image: uipathjenkinsdemo.azurecr.io/uipathrepository:latest
          endpoint: uipathjenkinsdemo

        steps:
          - script: C:\UiPath\UiRobot.exe pack $(Build.SourcesDirectory)\project.json -o $(Build.ArtifactStagingDirectory)\ -v 1.0.$(Build.BuildNumber)
            displayName: "Build the artifact"
          - publish: $(Build.ArtifactStagingDirectory)
            artifact: drop
            
  - stage: DeployUat
    displayName: Deploy build artifact to UAT
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: deployUat
        displayName: Deploy package to UAT Orchestrator
        pool:
          vmImage: "windows-latest"
        container:
          image: uipathjenkinsdemo.azurecr.io/uipathrepository:latest
          endpoint: uipathjenkinsdemo
        environment: uat
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    artifact: drop
                    path: $(Build.SourcesDirectory)/bin
                - powershell: |
                    Import-Module UiPath.Powershell
                    $token = Get-UiPathAuthToken -Verbose -ClientId $(uatClientId) -UserKey $(uatUserKey) -AccountName $(uatAccountName) -TenantName $(uatTenantName)
                    Add-UiPathPackage -PackageFile $(Build.SourcesDirectory)\bin\uipath-sample.1.0.$(Build.BuildNumber).nupkg -AuthToken $token